/** @format */

// START SIGNUP TYPES //
export const SIGN_UP_STUDENT_REQUEST = "SIGN_UP_STUDENT_REQUEST";
export const SIGN_UP_STUDENT_SUCCESS = "SIGN_UP_STUDENT_SUCCESS";
export const SIGN_UP_STUDENT_ERROR = "SIGN_UP_STUDENT_ERROR";

export const VERIFICATION_REQUEST = "VERIFICATION_REQUEST";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_ERROR = "VERIFICATION_ERROR";

export const SIGN_UP_TEACHER_REQUEST = "SIGN_UP_TEACHER_REQUEST";
export const SIGN_UP_TEACHER_SUCCESS = "SIGN_UP_TEACHER_SUCCESS";
export const SIGN_UP_TEACHER_ERROR = "SIGN_UP_TEACHER_ERROR";
// END SIGNUP TYPES //

// START LOGIN TYPES //
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
// END LOGIN TYPES //
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_ERROR = "ADMIN_LOGIN_ERROR";

export const NEWS_REQUEST = "NEWS_REQUEST";
export const NEWS_SUCCESS = "NEWS_SUCCESS";
export const NEWS_ERROR = "NEWS_ERROR";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const STUDENT_HOME_GET_REQUEST = "STUDENT_HOME_GET_REQUEST";
export const STUDENT_HOME_GET_SUCCESS = "STUDENT_HOME_GET_SUCCESS";
export const STUDENT_HOME_GET_ERROR = "STUDENT_HOME_GET_ERROR";