/** @format */

// START SIGNUP TYPES //
export const SIGN_UP_STUDENT_REQUEST = "SIGN_UP_STUDENT_REQUEST";
export const SIGN_UP_STUDENT_SUCCESS = "SIGN_UP_STUDENT_SUCCESS";
export const SIGN_UP_STUDENT_ERROR = "SIGN_UP_STUDENT_ERROR";

export const VERIFICATION_REQUEST = "VERIFICATION_REQUEST";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_ERROR = "VERIFICATION_ERROR";

export const SIGN_UP_TEACHER_REQUEST = "SIGN_UP_TEACHER_REQUEST";
export const SIGN_UP_TEACHER_SUCCESS = "SIGN_UP_TEACHER_SUCCESS";
export const SIGN_UP_TEACHER_ERROR = "SIGN_UP_TEACHER_ERROR";
// END SIGNUP TYPES //

// START LOGIN TYPES //
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
// END LOGIN TYPES //
